"""Inventory Reporting REST API (Step 10).

Standalone FastAPI application that serves the StoreInventoryReport
produced by the existing retail inventory pipeline.

Completely isolated from src/, main.py, and the crowd/queue pipeline.
Does NOT retrain or modify any model.

Endpoints
---------
GET /inventory/health          -- liveness check
GET /inventory/report          -- last cached report (instant, no pipeline run)
POST /inventory/run            -- re-run the pipeline, update cache, return report
GET /inventory/report/text     -- manager-readable text summary

Usage
-----
    # From the Retail_Analytics/ directory:
    python run_inventory_api.py

    # Or directly:
    uvicorn inventory.inventory_api:app --host 0.0.0.0 --port 8001 --reload
"""

from __future__ import annotations

import json
import pathlib
import sys
import threading
import time
from datetime import datetime, timezone
from typing import Any, Dict, Optional

# Ensure project root is on sys.path when imported as a module
ROOT_DIR = pathlib.Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from fastapi import BackgroundTasks, FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, PlainTextResponse

# ─── Default paths (relative to project root) ─────────────────────────────────
_DEFAULT_MODEL   = "inventory_data/custom_model/retail_detector_exp2.pt"
_DEFAULT_VIDEO   = "inventory_data/demo_videos/shelf_pan_demo.mp4"
_DEFAULT_CATALOG = "inventory_data/catalogs/demo_store_catalog.json"
_DEFAULT_JSON    = "output/inventory_report/inventory_report.json"

# ─── FastAPI application ───────────────────────────────────────────────────────
app = FastAPI(
    title="Retail Inventory API",
    description=(
        "Serves the StoreInventoryReport generated by the retail-specific "
        "inventory pipeline (Steps 1-8). Completely isolated from the "
        "crowd/queue analytics pipeline."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ─── In-memory report cache ────────────────────────────────────────────────────
_cache_lock     = threading.Lock()
_cached_report: Optional[Dict[str, Any]] = None
_cache_source   = "NONE"          # "DISK" | "PIPELINE" | "NONE"
_cache_timestamp: Optional[str]  = None
_pipeline_running = False


def _load_report_from_disk() -> Optional[Dict[str, Any]]:
    """Load the latest JSON report from disk if it exists."""
    p = ROOT_DIR / _DEFAULT_JSON
    if p.is_file():
        try:
            with open(p, encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return None
    return None


def _run_pipeline_sync(max_frames: int = 75) -> Dict[str, Any]:
    """Run the full inventory pipeline synchronously and return the report dict.

    Reuses all existing pipeline modules exactly as implemented in Steps 1-8.
    Does NOT modify any model weights, tracker, or crowd/queue code.
    """
    import cv2
    from inventory.catalog import SKUCatalog
    from inventory.config import InventoryModelConfig
    from inventory.inventory_aggregator import InventoryAggregatorConfig, SKUInventoryAggregator
    from inventory.inventory_alerts import InventoryAlertConfig, InventoryAlertDetector
    from inventory.inventory_events import InventoryEventConfig, InventoryEventDetector
    from inventory.inventory_report import StoreInventoryReportBuilder
    from inventory.shelf_detector import ShelfProductDetector
    from inventory.shelf_state import ProductTrackStateTracker

    model_path   = ROOT_DIR / _DEFAULT_MODEL
    video_path   = ROOT_DIR / _DEFAULT_VIDEO
    catalog_path = ROOT_DIR / _DEFAULT_CATALOG
    out_json     = ROOT_DIR / _DEFAULT_JSON

    if not model_path.is_file():
        raise FileNotFoundError(f"Detector model not found: {model_path}")
    if not video_path.is_file():
        raise FileNotFoundError(f"Demo video not found: {video_path}")

    # Initialise pipeline components (identical config to demo_inventory_report.py)
    det_cfg = InventoryModelConfig(
        model_path=str(model_path),
        model_tier="retail_specific",
        device="cpu",
        confidence_threshold=0.30,
        target_classes=None,
    )
    detector = ShelfProductDetector(det_cfg)

    catalog    = None
    recognizer = None
    if catalog_path.is_file():
        from inventory.sku_recognizer import SpatialColorTextureRecognizer
        catalog    = SKUCatalog.load_json(str(catalog_path))
        recognizer = SpatialColorTextureRecognizer(catalog=catalog, match_threshold=0.65)
        recognizer.build_index()

    tracker = ProductTrackStateTracker(
        min_hits_for_stable=3,
        max_misses_for_removal=5,
        displacement_change_ratio=0.25,
        iou_change_threshold=0.60,
    )
    event_detector = InventoryEventDetector(
        config=InventoryEventConfig(
            min_hits_for_stable=3,
            max_misses_for_removal=5,
            min_move_displacement_ratio=0.22,
            sustained_move_frames=2,
            sku_change_min_confidence=0.70,
            sku_recheck_interval=5,
        ),
        recognizer=recognizer,
    )
    aggregator = SKUInventoryAggregator(
        catalog=catalog,
        config=InventoryAggregatorConfig(
            in_stock_threshold=3,
            low_stock_threshold=2,
            snapshot_interval=15,
        ),
    )
    alert_detector = InventoryAlertDetector(
        config=InventoryAlertConfig(
            low_stock_threshold=2,
            stockout_consecutive_frames=10,
            rapid_removal_count=3,
            rapid_removal_window_frames=20,
            movement_alert_count=3,
            movement_window_frames=20,
            uncertain_sku_ratio_threshold=0.30,
            uncertain_sku_min_count=15,
            alert_cooldown_frames=15,
        ),
        catalog=catalog,
    )

    cap         = cv2.VideoCapture(str(video_path))
    fps         = cap.get(cv2.CAP_PROP_FPS) or 25.0
    total       = min(max_frames, int(cap.get(cv2.CAP_PROP_FRAME_COUNT)))
    frame_idx   = 0
    all_events  = []
    last_ts_sec = 0.0

    while cap.isOpened() and frame_idx < total:
        ret, frame = cap.read()
        if not ret or frame is None:
            break
        ts = frame_idx / fps
        last_ts_sec = ts

        batch    = detector.detect(frame=frame, frame_index=frame_idx, track=True, persist=True, tracker="bytetrack.yaml")
        snapshot = tracker.update(batch=batch, frame_index=frame_idx)
        evts     = event_detector.process_frame(batch=batch, snapshot=snapshot, frame_index=frame_idx, timestamp_sec=ts, frame_bgr=frame)
        all_events.extend(evts)
        sku_stats = aggregator.update(snapshot=snapshot, events=evts, frame_index=frame_idx, timestamp_sec=ts)
        alert_detector.process_frame(sku_stats=sku_stats, frame_events=evts, frame_index=frame_idx, timestamp_sec=ts)
        frame_idx += 1

    cap.release()

    report = StoreInventoryReportBuilder.build_report(
        sku_stats=aggregator.current_stats,
        all_alerts=alert_detector.all_alerts,
        recent_events=all_events,
        frame_index=frame_idx - 1,
        timestamp_sec=last_ts_sec,
        total_frames=frame_idx,
        video_source=str(video_path),
        catalog_skus_registered=len(catalog) if catalog else 0,
    )

    # Persist to disk
    report.save_json(out_json)
    return report.to_dict()


# ─── Startup: pre-warm cache from disk ────────────────────────────────────────
@app.on_event("startup")
def _startup_preload():
    global _cached_report, _cache_source, _cache_timestamp
    data = _load_report_from_disk()
    if data:
        with _cache_lock:
            _cached_report   = data
            _cache_source    = "DISK"
            _cache_timestamp = data.get("timestamp_iso") or datetime.now(timezone.utc).isoformat()


# ─── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/inventory/health", summary="Inventory API Health Check")
def inventory_health():
    """Verify the inventory API is alive and report cache status."""
    with _cache_lock:
        has_cache = _cached_report is not None
        source    = _cache_source
        ts        = _cache_timestamp
    return {
        "status":         "healthy",
        "report_cached":  has_cache,
        "cache_source":   source,
        "cache_timestamp": ts,
        "pipeline_running": _pipeline_running,
    }


@app.get("/inventory/report", summary="Get Latest Inventory Report")
def get_inventory_report():
    """Return the latest cached StoreInventoryReport JSON.

    On first call the report is loaded from disk (output/inventory_report/inventory_report.json).
    Call POST /inventory/run to regenerate it from the live pipeline.
    """
    global _cached_report, _cache_source, _cache_timestamp

    with _cache_lock:
        data   = _cached_report
        source = _cache_source
        ts     = _cache_timestamp

    if data is None:
        # Try loading from disk as a last resort
        data = _load_report_from_disk()
        if data is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=(
                    "No inventory report available. "
                    "Run POST /inventory/run to generate one, or run "
                    "scripts/demo_inventory_report.py first."
                ),
            )
        with _cache_lock:
            _cached_report   = data
            _cache_source    = "DISK"
            _cache_timestamp = data.get("timestamp_iso")
        source = "DISK"
        ts     = data.get("timestamp_iso")

    # Inject API metadata into response
    enriched = dict(data)
    enriched["_api_source"]    = source    # "DISK" | "PIPELINE"
    enriched["_api_served_at"] = datetime.now(timezone.utc).isoformat()
    enriched["_pipeline_running"] = _pipeline_running
    return JSONResponse(content=enriched)


@app.post("/inventory/run", summary="Re-run Inventory Pipeline")
def run_inventory_pipeline(background_tasks: BackgroundTasks, max_frames: int = 75):
    """Trigger a fresh pipeline run using the existing retail detector + ByteTrack.

    The pipeline runs in the background. Poll GET /inventory/report for the
    updated result, or check GET /inventory/health for pipeline_running status.

    This endpoint:
    - Does NOT retrain or modify any model.
    - Does NOT touch src/, configs/, or main.py.
    - Reuses all existing inventory modules exactly (Steps 1-8).
    """
    global _pipeline_running

    with _cache_lock:
        if _pipeline_running:
            return JSONResponse(
                status_code=status.HTTP_202_ACCEPTED,
                content={"status": "already_running", "message": "Pipeline already running. Poll GET /inventory/report."},
            )

    def _background_run():
        global _cached_report, _cache_source, _cache_timestamp, _pipeline_running
        _pipeline_running = True
        try:
            result = _run_pipeline_sync(max_frames=max_frames)
            with _cache_lock:
                _cached_report   = result
                _cache_source    = "PIPELINE"
                _cache_timestamp = result.get("timestamp_iso") or datetime.now(timezone.utc).isoformat()
        except Exception as exc:
            print(f"[InventoryAPI] Pipeline error: {exc}", flush=True)
        finally:
            _pipeline_running = False

    background_tasks.add_task(_background_run)
    return JSONResponse(
        status_code=status.HTTP_202_ACCEPTED,
        content={"status": "started", "message": "Pipeline running in background. Poll GET /inventory/report."},
    )


@app.get("/inventory/report/text", response_class=PlainTextResponse, summary="Manager Text Report")
def get_inventory_text():
    """Return the manager-readable text summary of the latest inventory report."""
    p = ROOT_DIR / "output" / "inventory_report" / "inventory_report.txt"
    if p.is_file():
        return p.read_text(encoding="utf-8")
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail="Text report not found. Run POST /inventory/run or scripts/demo_inventory_report.py first.",
    )
